// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/hosxp_pcu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCid struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *RequestCid) Reset() {
	*x = RequestCid{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCid) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCid) ProtoMessage() {}

func (x *RequestCid) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCid.ProtoReflect.Descriptor instead.
func (*RequestCid) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCid) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type RequestHospcode struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hospcode string `protobuf:"bytes,1,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
}

func (x *RequestHospcode) Reset() {
	*x = RequestHospcode{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestHospcode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestHospcode) ProtoMessage() {}

func (x *RequestHospcode) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestHospcode.ProtoReflect.Descriptor instead.
func (*RequestHospcode) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{1}
}

func (x *RequestHospcode) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

type RequestPatient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hn       string `protobuf:"bytes,1,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn       string `protobuf:"bytes,2,opt,name=vn,proto3" json:"vn,omitempty"`
	Hospcode string `protobuf:"bytes,3,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
}

func (x *RequestPatient) Reset() {
	*x = RequestPatient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPatient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPatient) ProtoMessage() {}

func (x *RequestPatient) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPatient.ProtoReflect.Descriptor instead.
func (*RequestPatient) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPatient) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *RequestPatient) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *RequestPatient) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*InfoResponse_Info `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{3}
}

func (x *InfoResponse) GetResults() []*InfoResponse_Info {
	if x != nil {
		return x.Results
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ServiceResponse_Service `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceResponse) GetResults() []*ServiceResponse_Service {
	if x != nil {
		return x.Results
	}
	return nil
}

type DoctorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DoctorResponse_Doctor `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{5}
}

func (x *DoctorResponse) GetResults() []*DoctorResponse_Doctor {
	if x != nil {
		return x.Results
	}
	return nil
}

type DiagnosisResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DiagnosisResponse_Diagnosis `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *DiagnosisResponse) Reset() {
	*x = DiagnosisResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosisResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisResponse) ProtoMessage() {}

func (x *DiagnosisResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisResponse.ProtoReflect.Descriptor instead.
func (*DiagnosisResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{6}
}

func (x *DiagnosisResponse) GetResults() []*DiagnosisResponse_Diagnosis {
	if x != nil {
		return x.Results
	}
	return nil
}

type ClinicResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ClinicResponse_Clinic `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *ClinicResponse) Reset() {
	*x = ClinicResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClinicResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicResponse) ProtoMessage() {}

func (x *ClinicResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicResponse.ProtoReflect.Descriptor instead.
func (*ClinicResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{7}
}

func (x *ClinicResponse) GetResults() []*ClinicResponse_Clinic {
	if x != nil {
		return x.Results
	}
	return nil
}

type ScreeningResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ScreeningResponse_Screening `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *ScreeningResponse) Reset() {
	*x = ScreeningResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreeningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningResponse) ProtoMessage() {}

func (x *ScreeningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningResponse.ProtoReflect.Descriptor instead.
func (*ScreeningResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{8}
}

func (x *ScreeningResponse) GetResults() []*ScreeningResponse_Screening {
	if x != nil {
		return x.Results
	}
	return nil
}

type ProcedureResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*ProcedureResponse_Procedure `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *ProcedureResponse) Reset() {
	*x = ProcedureResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResponse) ProtoMessage() {}

func (x *ProcedureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResponse.ProtoReflect.Descriptor instead.
func (*ProcedureResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{9}
}

func (x *ProcedureResponse) GetResults() []*ProcedureResponse_Procedure {
	if x != nil {
		return x.Results
	}
	return nil
}

type LabResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*LabResponse_Lab `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *LabResponse) Reset() {
	*x = LabResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabResponse) ProtoMessage() {}

func (x *LabResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabResponse.ProtoReflect.Descriptor instead.
func (*LabResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{10}
}

func (x *LabResponse) GetResults() []*LabResponse_Lab {
	if x != nil {
		return x.Results
	}
	return nil
}

type VaccineResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*VaccineResponse_Vaccine `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *VaccineResponse) Reset() {
	*x = VaccineResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaccineResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaccineResponse) ProtoMessage() {}

func (x *VaccineResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaccineResponse.ProtoReflect.Descriptor instead.
func (*VaccineResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{11}
}

func (x *VaccineResponse) GetResults() []*VaccineResponse_Vaccine {
	if x != nil {
		return x.Results
	}
	return nil
}

type DrugResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*DrugResponse_Drug `protobuf:"bytes,2,rep,name=Results,proto3" json:"Results,omitempty"`
}

func (x *DrugResponse) Reset() {
	*x = DrugResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrugResponse) ProtoMessage() {}

func (x *DrugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrugResponse.ProtoReflect.Descriptor instead.
func (*DrugResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{12}
}

func (x *DrugResponse) GetResults() []*DrugResponse_Drug {
	if x != nil {
		return x.Results
	}
	return nil
}

type InfoResponse_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	PatientHn  string `protobuf:"bytes,2,opt,name=patient_hn,json=patientHn,proto3" json:"patient_hn,omitempty"`
	Cid        string `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	GwHospcode string `protobuf:"bytes,4,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Pname      string `protobuf:"bytes,5,opt,name=pname,proto3" json:"pname,omitempty"`
	Fname      string `protobuf:"bytes,6,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname      string `protobuf:"bytes,7,opt,name=lname,proto3" json:"lname,omitempty"`
	Birthdate  string `protobuf:"bytes,8,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
}

func (x *InfoResponse_Info) Reset() {
	*x = InfoResponse_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse_Info) ProtoMessage() {}

func (x *InfoResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse_Info.ProtoReflect.Descriptor instead.
func (*InfoResponse_Info) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{3, 0}
}

func (x *InfoResponse_Info) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *InfoResponse_Info) GetPatientHn() string {
	if x != nil {
		return x.PatientHn
	}
	return ""
}

func (x *InfoResponse_Info) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *InfoResponse_Info) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *InfoResponse_Info) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *InfoResponse_Info) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *InfoResponse_Info) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *InfoResponse_Info) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type ServiceResponse_Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn         string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn         string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	Vstdate    string `protobuf:"bytes,5,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime    string `protobuf:"bytes,6,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Pttype     string `protobuf:"bytes,7,opt,name=pttype,proto3" json:"pttype,omitempty"`
	Pttypeno   string `protobuf:"bytes,8,opt,name=pttypeno,proto3" json:"pttypeno,omitempty"`
	Spclty     string `protobuf:"bytes,9,opt,name=spclty,proto3" json:"spclty,omitempty"`
	Hospname   string `protobuf:"bytes,10,opt,name=hospname,proto3" json:"hospname,omitempty"`
}

func (x *ServiceResponse_Service) Reset() {
	*x = ServiceResponse_Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse_Service) ProtoMessage() {}

func (x *ServiceResponse_Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse_Service.ProtoReflect.Descriptor instead.
func (*ServiceResponse_Service) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{4, 0}
}

func (x *ServiceResponse_Service) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *ServiceResponse_Service) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *ServiceResponse_Service) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ServiceResponse_Service) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *ServiceResponse_Service) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *ServiceResponse_Service) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *ServiceResponse_Service) GetPttype() string {
	if x != nil {
		return x.Pttype
	}
	return ""
}

func (x *ServiceResponse_Service) GetPttypeno() string {
	if x != nil {
		return x.Pttypeno
	}
	return ""
}

func (x *ServiceResponse_Service) GetSpclty() string {
	if x != nil {
		return x.Spclty
	}
	return ""
}

func (x *ServiceResponse_Service) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

type DoctorResponse_Doctor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Name       string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	LicenseNo  string `protobuf:"bytes,4,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	Cid        string `protobuf:"bytes,5,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *DoctorResponse_Doctor) Reset() {
	*x = DoctorResponse_Doctor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoctorResponse_Doctor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse_Doctor) ProtoMessage() {}

func (x *DoctorResponse_Doctor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse_Doctor.ProtoReflect.Descriptor instead.
func (*DoctorResponse_Doctor) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{5, 0}
}

func (x *DoctorResponse_Doctor) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *DoctorResponse_Doctor) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *DoctorResponse_Doctor) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DoctorResponse_Doctor) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *DoctorResponse_Doctor) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type DiagnosisResponse_Diagnosis struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn         string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn         string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	Vstdate    string `protobuf:"bytes,5,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime    string `protobuf:"bytes,6,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Hospname   string `protobuf:"bytes,7,opt,name=hospname,proto3" json:"hospname,omitempty"`
	Diagename  string `protobuf:"bytes,8,opt,name=diagename,proto3" json:"diagename,omitempty"`
	Diagtname  string `protobuf:"bytes,9,opt,name=diagtname,proto3" json:"diagtname,omitempty"`
}

func (x *DiagnosisResponse_Diagnosis) Reset() {
	*x = DiagnosisResponse_Diagnosis{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiagnosisResponse_Diagnosis) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiagnosisResponse_Diagnosis) ProtoMessage() {}

func (x *DiagnosisResponse_Diagnosis) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiagnosisResponse_Diagnosis.ProtoReflect.Descriptor instead.
func (*DiagnosisResponse_Diagnosis) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DiagnosisResponse_Diagnosis) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetDiagename() string {
	if x != nil {
		return x.Diagename
	}
	return ""
}

func (x *DiagnosisResponse_Diagnosis) GetDiagtname() string {
	if x != nil {
		return x.Diagtname
	}
	return ""
}

type ClinicResponse_Clinic struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	ClinicCode string `protobuf:"bytes,3,opt,name=clinic_code,json=clinicCode,proto3" json:"clinic_code,omitempty"`
	ClinicName string `protobuf:"bytes,4,opt,name=clinic_name,json=clinicName,proto3" json:"clinic_name,omitempty"`
}

func (x *ClinicResponse_Clinic) Reset() {
	*x = ClinicResponse_Clinic{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClinicResponse_Clinic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClinicResponse_Clinic) ProtoMessage() {}

func (x *ClinicResponse_Clinic) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClinicResponse_Clinic.ProtoReflect.Descriptor instead.
func (*ClinicResponse_Clinic) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{7, 0}
}

func (x *ClinicResponse_Clinic) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *ClinicResponse_Clinic) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *ClinicResponse_Clinic) GetClinicCode() string {
	if x != nil {
		return x.ClinicCode
	}
	return ""
}

func (x *ClinicResponse_Clinic) GetClinicName() string {
	if x != nil {
		return x.ClinicName
	}
	return ""
}

type ScreeningResponse_Screening struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn         string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn         string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	Vstdate    string `protobuf:"bytes,5,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime    string `protobuf:"bytes,6,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Hospname   string `protobuf:"bytes,7,opt,name=hospname,proto3" json:"hospname,omitempty"`
}

func (x *ScreeningResponse_Screening) Reset() {
	*x = ScreeningResponse_Screening{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ScreeningResponse_Screening) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreeningResponse_Screening) ProtoMessage() {}

func (x *ScreeningResponse_Screening) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreeningResponse_Screening.ProtoReflect.Descriptor instead.
func (*ScreeningResponse_Screening) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{8, 0}
}

func (x *ScreeningResponse_Screening) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *ScreeningResponse_Screening) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

type ProcedureResponse_Procedure struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn         string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn         string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	Vstdate    string `protobuf:"bytes,5,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime    string `protobuf:"bytes,6,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Hospname   string `protobuf:"bytes,7,opt,name=hospname,proto3" json:"hospname,omitempty"`
	Diagename  string `protobuf:"bytes,8,opt,name=diagename,proto3" json:"diagename,omitempty"`
	Diagtname  string `protobuf:"bytes,9,opt,name=diagtname,proto3" json:"diagtname,omitempty"`
}

func (x *ProcedureResponse_Procedure) Reset() {
	*x = ProcedureResponse_Procedure{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProcedureResponse_Procedure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcedureResponse_Procedure) ProtoMessage() {}

func (x *ProcedureResponse_Procedure) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcedureResponse_Procedure.ProtoReflect.Descriptor instead.
func (*ProcedureResponse_Procedure) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{9, 0}
}

func (x *ProcedureResponse_Procedure) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetDiagename() string {
	if x != nil {
		return x.Diagename
	}
	return ""
}

func (x *ProcedureResponse_Procedure) GetDiagtname() string {
	if x != nil {
		return x.Diagtname
	}
	return ""
}

type LabResponse_Lab struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId             string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode             string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn                     string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn                     string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	LabItemsCode           string `protobuf:"bytes,5,opt,name=lab_items_code,json=labItemsCode,proto3" json:"lab_items_code,omitempty"`
	LabItemsNameRef        string `protobuf:"bytes,6,opt,name=lab_items_name_ref,json=labItemsNameRef,proto3" json:"lab_items_name_ref,omitempty"`
	LabItemsNormalValueRef string `protobuf:"bytes,7,opt,name=lab_items_normal_value_ref,json=labItemsNormalValueRef,proto3" json:"lab_items_normal_value_ref,omitempty"`
	Hospname               string `protobuf:"bytes,8,opt,name=hospname,proto3" json:"hospname,omitempty"`
	LabItemsName           string `protobuf:"bytes,9,opt,name=lab_items_name,json=labItemsName,proto3" json:"lab_items_name,omitempty"`
	LabItemsUnit           string `protobuf:"bytes,10,opt,name=lab_items_unit,json=labItemsUnit,proto3" json:"lab_items_unit,omitempty"`
	LabItemsNormalValue    string `protobuf:"bytes,11,opt,name=lab_items_normal_value,json=labItemsNormalValue,proto3" json:"lab_items_normal_value,omitempty"`
}

func (x *LabResponse_Lab) Reset() {
	*x = LabResponse_Lab{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LabResponse_Lab) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabResponse_Lab) ProtoMessage() {}

func (x *LabResponse_Lab) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabResponse_Lab.ProtoReflect.Descriptor instead.
func (*LabResponse_Lab) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{10, 0}
}

func (x *LabResponse_Lab) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *LabResponse_Lab) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *LabResponse_Lab) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *LabResponse_Lab) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsCode() string {
	if x != nil {
		return x.LabItemsCode
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsNameRef() string {
	if x != nil {
		return x.LabItemsNameRef
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsNormalValueRef() string {
	if x != nil {
		return x.LabItemsNormalValueRef
	}
	return ""
}

func (x *LabResponse_Lab) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsName() string {
	if x != nil {
		return x.LabItemsName
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsUnit() string {
	if x != nil {
		return x.LabItemsUnit
	}
	return ""
}

func (x *LabResponse_Lab) GetLabItemsNormalValue() string {
	if x != nil {
		return x.LabItemsNormalValue
	}
	return ""
}

type VaccineResponse_Vaccine struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId   string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode   string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn           string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn           string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	VaccineNote  string `protobuf:"bytes,5,opt,name=vaccine_note,json=vaccineNote,proto3" json:"vaccine_note,omitempty"`
	AbnormalNote string `protobuf:"bytes,6,opt,name=abnormal_note,json=abnormalNote,proto3" json:"abnormal_note,omitempty"`
}

func (x *VaccineResponse_Vaccine) Reset() {
	*x = VaccineResponse_Vaccine{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VaccineResponse_Vaccine) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaccineResponse_Vaccine) ProtoMessage() {}

func (x *VaccineResponse_Vaccine) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaccineResponse_Vaccine.ProtoReflect.Descriptor instead.
func (*VaccineResponse_Vaccine) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{11, 0}
}

func (x *VaccineResponse_Vaccine) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *VaccineResponse_Vaccine) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *VaccineResponse_Vaccine) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *VaccineResponse_Vaccine) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *VaccineResponse_Vaccine) GetVaccineNote() string {
	if x != nil {
		return x.VaccineNote
	}
	return ""
}

func (x *VaccineResponse_Vaccine) GetAbnormalNote() string {
	if x != nil {
		return x.AbnormalNote
	}
	return ""
}

type DrugResponse_Drug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GwRecordId string `protobuf:"bytes,1,opt,name=gw_record_id,json=gwRecordId,proto3" json:"gw_record_id,omitempty"`
	GwHospcode string `protobuf:"bytes,2,opt,name=gw_hospcode,json=gwHospcode,proto3" json:"gw_hospcode,omitempty"`
	Hn         string `protobuf:"bytes,3,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn         string `protobuf:"bytes,4,opt,name=vn,proto3" json:"vn,omitempty"`
	Icode      string `protobuf:"bytes,5,opt,name=icode,proto3" json:"icode,omitempty"`
	Qty        string `protobuf:"bytes,6,opt,name=qty,proto3" json:"qty,omitempty"`
	Unitprice  string `protobuf:"bytes,7,opt,name=unitprice,proto3" json:"unitprice,omitempty"`
	Vstdate    string `protobuf:"bytes,8,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime    string `protobuf:"bytes,9,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Hospname   string `protobuf:"bytes,10,opt,name=hospname,proto3" json:"hospname,omitempty"`
}

func (x *DrugResponse_Drug) Reset() {
	*x = DrugResponse_Drug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_pcu_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DrugResponse_Drug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DrugResponse_Drug) ProtoMessage() {}

func (x *DrugResponse_Drug) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_pcu_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DrugResponse_Drug.ProtoReflect.Descriptor instead.
func (*DrugResponse_Drug) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_pcu_proto_rawDescGZIP(), []int{12, 0}
}

func (x *DrugResponse_Drug) GetGwRecordId() string {
	if x != nil {
		return x.GwRecordId
	}
	return ""
}

func (x *DrugResponse_Drug) GetGwHospcode() string {
	if x != nil {
		return x.GwHospcode
	}
	return ""
}

func (x *DrugResponse_Drug) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *DrugResponse_Drug) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *DrugResponse_Drug) GetIcode() string {
	if x != nil {
		return x.Icode
	}
	return ""
}

func (x *DrugResponse_Drug) GetQty() string {
	if x != nil {
		return x.Qty
	}
	return ""
}

func (x *DrugResponse_Drug) GetUnitprice() string {
	if x != nil {
		return x.Unitprice
	}
	return ""
}

func (x *DrugResponse_Drug) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *DrugResponse_Drug) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *DrugResponse_Drug) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

var File_proto_hosxp_pcu_proto protoreflect.FileDescriptor

var file_proto_hosxp_pcu_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x73, 0x78, 0x70, 0x5f, 0x70, 0x63,
	0x75, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1e,
	0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x69, 0x64, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x2d,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x4c, 0x0a,
	0x0e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12,
	0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x22, 0x9f, 0x02, 0x0a, 0x0c,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x1a, 0xda, 0x01, 0x0a, 0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x48, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x22, 0xd6, 0x02,
	0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x88, 0x02, 0x0a, 0x07,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f,
	0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x70, 0x74, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65,
	0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65,
	0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x70, 0x63, 0x6c, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x70, 0x63, 0x6c, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xdb, 0x01, 0x0a, 0x0e, 0x44, 0x6f, 0x63, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x1a, 0x90, 0x01, 0x0a, 0x06, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x12, 0x20, 0x0a, 0x0c,
	0x67, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f,
	0x0a, 0x0b, 0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65, 0x5f, 0x6e,
	0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6c, 0x69, 0x63, 0x65, 0x6e, 0x73, 0x65,
	0x4e, 0x6f, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x63, 0x69, 0x64, 0x22, 0xce, 0x02, 0x0a, 0x11, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x52,
	0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xfa, 0x01, 0x0a, 0x09, 0x44, 0x69, 0x61,
	0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77,
	0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f, 0x68,
	0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x64,
	0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x61,
	0x67, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69,
	0x61, 0x67, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x67, 0x74,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x61, 0x67,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xd8, 0x01, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x1a, 0x8d, 0x01, 0x0a, 0x06, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x12, 0x20, 0x0a, 0x0c, 0x67,
	0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x1f,
	0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x43, 0x6f, 0x64, 0x65, 0x12,
	0x1f, 0x0a, 0x0b, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x4e, 0x61, 0x6d, 0x65,
	0x22, 0x92, 0x02, 0x0a, 0x11, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x07, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x73, 0x1a, 0xbe, 0x01, 0x0a, 0x09, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69,
	0x6e, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xce, 0x02, 0x0a, 0x11, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64,
	0x75, 0x72, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65,
	0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xfa, 0x01, 0x0a, 0x09, 0x50, 0x72,
	0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67,
	0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f,
	0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74,
	0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69,
	0x61, 0x67, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64,
	0x69, 0x61, 0x67, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x61, 0x67,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x61,
	0x67, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xd6, 0x03, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x4c, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x4c, 0x61, 0x62, 0x52,
	0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0x94, 0x03, 0x0a, 0x03, 0x4c, 0x61, 0x62,
	0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x76, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x62, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73,
	0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x62,
	0x49, 0x74, 0x65, 0x6d, 0x73, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x2b, 0x0a, 0x12, 0x6c, 0x61, 0x62,
	0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x5f, 0x72, 0x65, 0x66, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x6c, 0x61, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x4e,
	0x61, 0x6d, 0x65, 0x52, 0x65, 0x66, 0x12, 0x3a, 0x0a, 0x1a, 0x6c, 0x61, 0x62, 0x5f, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x5f, 0x72, 0x65, 0x66, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x16, 0x6c, 0x61, 0x62, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x52,
	0x65, 0x66, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24,
	0x0a, 0x0e, 0x6c, 0x61, 0x62, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61, 0x62, 0x49, 0x74, 0x65, 0x6d, 0x73,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x0e, 0x6c, 0x61, 0x62, 0x5f, 0x69, 0x74, 0x65, 0x6d,
	0x73, 0x5f, 0x75, 0x6e, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6c, 0x61,
	0x62, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x55, 0x6e, 0x69, 0x74, 0x12, 0x33, 0x0a, 0x16, 0x6c, 0x61,
	0x62, 0x5f, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x5f, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x13, 0x6c, 0x61, 0x62, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x4e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x22,
	0x82, 0x02, 0x0a, 0x0f, 0x56, 0x61, 0x63, 0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x63,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x56, 0x61, 0x63,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xb4, 0x01,
	0x0a, 0x07, 0x56, 0x61, 0x63, 0x63, 0x69, 0x6e, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67,
	0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02,
	0x68, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02,
	0x76, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x21, 0x0a, 0x0c,
	0x76, 0x61, 0x63, 0x63, 0x69, 0x6e, 0x65, 0x5f, 0x6e, 0x6f, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x76, 0x61, 0x63, 0x63, 0x69, 0x6e, 0x65, 0x4e, 0x6f, 0x74, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x5f, 0x6e, 0x6f, 0x74, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x61, 0x62, 0x6e, 0x6f, 0x72, 0x6d, 0x61, 0x6c,
	0x4e, 0x6f, 0x74, 0x65, 0x22, 0xc4, 0x02, 0x0a, 0x0c, 0x44, 0x72, 0x75, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44,
	0x72, 0x75, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x72, 0x75, 0x67,
	0x52, 0x07, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xff, 0x01, 0x0a, 0x04, 0x44, 0x72,
	0x75, 0x67, 0x12, 0x20, 0x0a, 0x0c, 0x67, 0x77, 0x5f, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x52, 0x65, 0x63, 0x6f,
	0x72, 0x64, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x67, 0x77, 0x5f, 0x68, 0x6f, 0x73, 0x70, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x67, 0x77, 0x48, 0x6f, 0x73,
	0x70, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x71,
	0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x71, 0x74, 0x79, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x6e, 0x69, 0x74, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x75, 0x6e, 0x69, 0x74, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76,
	0x73, 0x74, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73,
	0x74, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x32, 0xf9, 0x03, 0x0a, 0x0a,
	0x45, 0x6d, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x37, 0x0a, 0x0b, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x69, 0x64, 0x1a, 0x13, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x3a, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x12, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x43, 0x69, 0x64, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x53, 0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x12,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53,
	0x63, 0x72, 0x65, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73,
	0x69, 0x73, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x44, 0x69, 0x61, 0x67, 0x6e, 0x6f, 0x73, 0x69, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x50, 0x72, 0x6f, 0x63,
	0x65, 0x64, 0x75, 0x72, 0x65, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x64, 0x75, 0x72, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x35, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4c,
	0x61, 0x62, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x12, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x4c, 0x61, 0x62, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x3d, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x56, 0x61, 0x63, 0x63, 0x69, 0x6e, 0x65, 0x12, 0x15, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x56, 0x61, 0x63,
	0x63, 0x69, 0x6e, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x37,
	0x0a, 0x07, 0x47, 0x65, 0x74, 0x44, 0x72, 0x75, 0x67, 0x12, 0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x1a, 0x13, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x72, 0x75, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x32, 0x8d, 0x01, 0x0a, 0x0d, 0x4d, 0x61, 0x73, 0x74,
	0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x44, 0x6f, 0x63,
	0x74, 0x6f, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x1a,
	0x15, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x44, 0x6f, 0x63, 0x74, 0x6f, 0x72, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x3d, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x6e,
	0x69, 0x63, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0x15,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x43, 0x6c, 0x69, 0x6e, 0x69, 0x63, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hosxp_pcu_proto_rawDescOnce sync.Once
	file_proto_hosxp_pcu_proto_rawDescData = file_proto_hosxp_pcu_proto_rawDesc
)

func file_proto_hosxp_pcu_proto_rawDescGZIP() []byte {
	file_proto_hosxp_pcu_proto_rawDescOnce.Do(func() {
		file_proto_hosxp_pcu_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hosxp_pcu_proto_rawDescData)
	})
	return file_proto_hosxp_pcu_proto_rawDescData
}

var file_proto_hosxp_pcu_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_hosxp_pcu_proto_goTypes = []interface{}{
	(*RequestCid)(nil),                  // 0: proto.RequestCid
	(*RequestHospcode)(nil),             // 1: proto.RequestHospcode
	(*RequestPatient)(nil),              // 2: proto.RequestPatient
	(*InfoResponse)(nil),                // 3: proto.InfoResponse
	(*ServiceResponse)(nil),             // 4: proto.ServiceResponse
	(*DoctorResponse)(nil),              // 5: proto.DoctorResponse
	(*DiagnosisResponse)(nil),           // 6: proto.DiagnosisResponse
	(*ClinicResponse)(nil),              // 7: proto.ClinicResponse
	(*ScreeningResponse)(nil),           // 8: proto.ScreeningResponse
	(*ProcedureResponse)(nil),           // 9: proto.ProcedureResponse
	(*LabResponse)(nil),                 // 10: proto.LabResponse
	(*VaccineResponse)(nil),             // 11: proto.VaccineResponse
	(*DrugResponse)(nil),                // 12: proto.DrugResponse
	(*InfoResponse_Info)(nil),           // 13: proto.InfoResponse.Info
	(*ServiceResponse_Service)(nil),     // 14: proto.ServiceResponse.Service
	(*DoctorResponse_Doctor)(nil),       // 15: proto.DoctorResponse.Doctor
	(*DiagnosisResponse_Diagnosis)(nil), // 16: proto.DiagnosisResponse.Diagnosis
	(*ClinicResponse_Clinic)(nil),       // 17: proto.ClinicResponse.Clinic
	(*ScreeningResponse_Screening)(nil), // 18: proto.ScreeningResponse.Screening
	(*ProcedureResponse_Procedure)(nil), // 19: proto.ProcedureResponse.Procedure
	(*LabResponse_Lab)(nil),             // 20: proto.LabResponse.Lab
	(*VaccineResponse_Vaccine)(nil),     // 21: proto.VaccineResponse.Vaccine
	(*DrugResponse_Drug)(nil),           // 22: proto.DrugResponse.Drug
}
var file_proto_hosxp_pcu_proto_depIdxs = []int32{
	13, // 0: proto.InfoResponse.Results:type_name -> proto.InfoResponse.Info
	14, // 1: proto.ServiceResponse.Results:type_name -> proto.ServiceResponse.Service
	15, // 2: proto.DoctorResponse.Results:type_name -> proto.DoctorResponse.Doctor
	16, // 3: proto.DiagnosisResponse.Results:type_name -> proto.DiagnosisResponse.Diagnosis
	17, // 4: proto.ClinicResponse.Results:type_name -> proto.ClinicResponse.Clinic
	18, // 5: proto.ScreeningResponse.Results:type_name -> proto.ScreeningResponse.Screening
	19, // 6: proto.ProcedureResponse.Results:type_name -> proto.ProcedureResponse.Procedure
	20, // 7: proto.LabResponse.Results:type_name -> proto.LabResponse.Lab
	21, // 8: proto.VaccineResponse.Results:type_name -> proto.VaccineResponse.Vaccine
	22, // 9: proto.DrugResponse.Results:type_name -> proto.DrugResponse.Drug
	0,  // 10: proto.EmrService.PatientInfo:input_type -> proto.RequestCid
	0,  // 11: proto.EmrService.GetServices:input_type -> proto.RequestCid
	2,  // 12: proto.EmrService.GetScreening:input_type -> proto.RequestPatient
	2,  // 13: proto.EmrService.GetDiagnosis:input_type -> proto.RequestPatient
	2,  // 14: proto.EmrService.GetProcedure:input_type -> proto.RequestPatient
	2,  // 15: proto.EmrService.GetLab:input_type -> proto.RequestPatient
	2,  // 16: proto.EmrService.GetVaccine:input_type -> proto.RequestPatient
	2,  // 17: proto.EmrService.GetDrug:input_type -> proto.RequestPatient
	1,  // 18: proto.MasterService.DoctorList:input_type -> proto.RequestHospcode
	1,  // 19: proto.MasterService.ClinicList:input_type -> proto.RequestHospcode
	3,  // 20: proto.EmrService.PatientInfo:output_type -> proto.InfoResponse
	4,  // 21: proto.EmrService.GetServices:output_type -> proto.ServiceResponse
	8,  // 22: proto.EmrService.GetScreening:output_type -> proto.ScreeningResponse
	6,  // 23: proto.EmrService.GetDiagnosis:output_type -> proto.DiagnosisResponse
	9,  // 24: proto.EmrService.GetProcedure:output_type -> proto.ProcedureResponse
	10, // 25: proto.EmrService.GetLab:output_type -> proto.LabResponse
	11, // 26: proto.EmrService.GetVaccine:output_type -> proto.VaccineResponse
	12, // 27: proto.EmrService.GetDrug:output_type -> proto.DrugResponse
	5,  // 28: proto.MasterService.DoctorList:output_type -> proto.DoctorResponse
	7,  // 29: proto.MasterService.ClinicList:output_type -> proto.ClinicResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_hosxp_pcu_proto_init() }
func file_proto_hosxp_pcu_proto_init() {
	if File_proto_hosxp_pcu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hosxp_pcu_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCid); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestHospcode); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPatient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosisResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClinicResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreeningResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaccineResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrugResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse_Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoctorResponse_Doctor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiagnosisResponse_Diagnosis); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClinicResponse_Clinic); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ScreeningResponse_Screening); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProcedureResponse_Procedure); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LabResponse_Lab); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VaccineResponse_Vaccine); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_pcu_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DrugResponse_Drug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hosxp_pcu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_hosxp_pcu_proto_goTypes,
		DependencyIndexes: file_proto_hosxp_pcu_proto_depIdxs,
		MessageInfos:      file_proto_hosxp_pcu_proto_msgTypes,
	}.Build()
	File_proto_hosxp_pcu_proto = out.File
	file_proto_hosxp_pcu_proto_rawDesc = nil
	file_proto_hosxp_pcu_proto_goTypes = nil
	file_proto_hosxp_pcu_proto_depIdxs = nil
}
