// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: proto/hosxp.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// option go_package = "example.com/foo/bar";
type Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cid string `protobuf:"bytes,1,opt,name=cid,proto3" json:"cid,omitempty"`
}

func (x *Request) Reset() {
	*x = Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

type InfoResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Results []*InfoResponse_Info `protobuf:"bytes,2,rep,name=results,proto3" json:"results,omitempty"`
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetResults() []*InfoResponse_Info {
	if x != nil {
		return x.Results
	}
	return nil
}

type ServiceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Services []*ServiceResponse_Service `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
}

func (x *ServiceResponse) Reset() {
	*x = ServiceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse) ProtoMessage() {}

func (x *ServiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse.ProtoReflect.Descriptor instead.
func (*ServiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_proto_rawDescGZIP(), []int{2}
}

func (x *ServiceResponse) GetServices() []*ServiceResponse_Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type InfoResponse_Info struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId  string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	PatientHn string `protobuf:"bytes,2,opt,name=patient_hn,json=patientHn,proto3" json:"patient_hn,omitempty"`
	Cid       string `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Hospcode  string `protobuf:"bytes,4,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Pname     string `protobuf:"bytes,5,opt,name=pname,proto3" json:"pname,omitempty"`
	Fname     string `protobuf:"bytes,6,opt,name=fname,proto3" json:"fname,omitempty"`
	Lname     string `protobuf:"bytes,7,opt,name=lname,proto3" json:"lname,omitempty"`
	Birthdate string `protobuf:"bytes,8,opt,name=birthdate,proto3" json:"birthdate,omitempty"`
}

func (x *InfoResponse_Info) Reset() {
	*x = InfoResponse_Info{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoResponse_Info) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse_Info) ProtoMessage() {}

func (x *InfoResponse_Info) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse_Info.ProtoReflect.Descriptor instead.
func (*InfoResponse_Info) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_proto_rawDescGZIP(), []int{1, 0}
}

func (x *InfoResponse_Info) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *InfoResponse_Info) GetPatientHn() string {
	if x != nil {
		return x.PatientHn
	}
	return ""
}

func (x *InfoResponse_Info) GetCid() string {
	if x != nil {
		return x.Cid
	}
	return ""
}

func (x *InfoResponse_Info) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *InfoResponse_Info) GetPname() string {
	if x != nil {
		return x.Pname
	}
	return ""
}

func (x *InfoResponse_Info) GetFname() string {
	if x != nil {
		return x.Fname
	}
	return ""
}

func (x *InfoResponse_Info) GetLname() string {
	if x != nil {
		return x.Lname
	}
	return ""
}

func (x *InfoResponse_Info) GetBirthdate() string {
	if x != nil {
		return x.Birthdate
	}
	return ""
}

type ServiceResponse_Service struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecordId string `protobuf:"bytes,1,opt,name=record_id,json=recordId,proto3" json:"record_id,omitempty"`
	Hn       string `protobuf:"bytes,2,opt,name=hn,proto3" json:"hn,omitempty"`
	Vn       string `protobuf:"bytes,3,opt,name=vn,proto3" json:"vn,omitempty"`
	Hospcode string `protobuf:"bytes,4,opt,name=hospcode,proto3" json:"hospcode,omitempty"`
	Vstdate  string `protobuf:"bytes,5,opt,name=vstdate,proto3" json:"vstdate,omitempty"`
	Vsttime  string `protobuf:"bytes,6,opt,name=vsttime,proto3" json:"vsttime,omitempty"`
	Pttype   string `protobuf:"bytes,7,opt,name=pttype,proto3" json:"pttype,omitempty"`
	Pttypeno string `protobuf:"bytes,8,opt,name=pttypeno,proto3" json:"pttypeno,omitempty"`
	Spclty   string `protobuf:"bytes,9,opt,name=spclty,proto3" json:"spclty,omitempty"`
	Hospname string `protobuf:"bytes,10,opt,name=hospname,proto3" json:"hospname,omitempty"`
}

func (x *ServiceResponse_Service) Reset() {
	*x = ServiceResponse_Service{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_hosxp_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServiceResponse_Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceResponse_Service) ProtoMessage() {}

func (x *ServiceResponse_Service) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hosxp_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceResponse_Service.ProtoReflect.Descriptor instead.
func (*ServiceResponse_Service) Descriptor() ([]byte, []int) {
	return file_proto_hosxp_proto_rawDescGZIP(), []int{2, 0}
}

func (x *ServiceResponse_Service) GetRecordId() string {
	if x != nil {
		return x.RecordId
	}
	return ""
}

func (x *ServiceResponse_Service) GetHn() string {
	if x != nil {
		return x.Hn
	}
	return ""
}

func (x *ServiceResponse_Service) GetVn() string {
	if x != nil {
		return x.Vn
	}
	return ""
}

func (x *ServiceResponse_Service) GetHospcode() string {
	if x != nil {
		return x.Hospcode
	}
	return ""
}

func (x *ServiceResponse_Service) GetVstdate() string {
	if x != nil {
		return x.Vstdate
	}
	return ""
}

func (x *ServiceResponse_Service) GetVsttime() string {
	if x != nil {
		return x.Vsttime
	}
	return ""
}

func (x *ServiceResponse_Service) GetPttype() string {
	if x != nil {
		return x.Pttype
	}
	return ""
}

func (x *ServiceResponse_Service) GetPttypeno() string {
	if x != nil {
		return x.Pttypeno
	}
	return ""
}

func (x *ServiceResponse_Service) GetSpclty() string {
	if x != nil {
		return x.Spclty
	}
	return ""
}

func (x *ServiceResponse_Service) GetHospname() string {
	if x != nil {
		return x.Hospname
	}
	return ""
}

var File_proto_hosxp_proto protoreflect.FileDescriptor

var file_proto_hosxp_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x68, 0x6f, 0x73, 0x78, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1b, 0x0a, 0x07, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x63, 0x69, 0x64, 0x22, 0x95, 0x02, 0x0a, 0x0c, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x32, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x1a, 0xd0, 0x01, 0x0a,
	0x04, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x72, 0x65, 0x63, 0x6f, 0x72, 0x64,
	0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x48,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6c,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x6e, 0x61, 0x6d,
	0x65, 0x12, 0x1c, 0x0a, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x69, 0x72, 0x74, 0x68, 0x64, 0x61, 0x74, 0x65, 0x22,
	0xce, 0x02, 0x0a, 0x0f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x3a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x1a,
	0xfe, 0x01, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x72,
	0x65, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x68, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x68, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x76, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x76, 0x73, 0x74, 0x64, 0x61, 0x74, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x76, 0x73, 0x74, 0x74, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x74, 0x74, 0x79,
	0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65, 0x6e, 0x6f, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x74, 0x74, 0x79, 0x70, 0x65, 0x6e, 0x6f, 0x12, 0x16, 0x0a, 0x06,
	0x73, 0x70, 0x63, 0x6c, 0x74, 0x79, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x70,
	0x63, 0x6c, 0x74, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x6e, 0x61, 0x6d, 0x65,
	0x32, 0x7b, 0x0a, 0x0a, 0x45, 0x6d, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x34,
	0x0a, 0x0b, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_hosxp_proto_rawDescOnce sync.Once
	file_proto_hosxp_proto_rawDescData = file_proto_hosxp_proto_rawDesc
)

func file_proto_hosxp_proto_rawDescGZIP() []byte {
	file_proto_hosxp_proto_rawDescOnce.Do(func() {
		file_proto_hosxp_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_hosxp_proto_rawDescData)
	})
	return file_proto_hosxp_proto_rawDescData
}

var file_proto_hosxp_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_hosxp_proto_goTypes = []interface{}{
	(*Request)(nil),                 // 0: proto.Request
	(*InfoResponse)(nil),            // 1: proto.InfoResponse
	(*ServiceResponse)(nil),         // 2: proto.ServiceResponse
	(*InfoResponse_Info)(nil),       // 3: proto.InfoResponse.Info
	(*ServiceResponse_Service)(nil), // 4: proto.ServiceResponse.Service
}
var file_proto_hosxp_proto_depIdxs = []int32{
	3, // 0: proto.InfoResponse.results:type_name -> proto.InfoResponse.Info
	4, // 1: proto.ServiceResponse.services:type_name -> proto.ServiceResponse.Service
	0, // 2: proto.EmrService.PatientInfo:input_type -> proto.Request
	0, // 3: proto.EmrService.GetServices:input_type -> proto.Request
	1, // 4: proto.EmrService.PatientInfo:output_type -> proto.InfoResponse
	2, // 5: proto.EmrService.GetServices:output_type -> proto.ServiceResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hosxp_proto_init() }
func file_proto_hosxp_proto_init() {
	if File_proto_hosxp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_hosxp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoResponse_Info); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_hosxp_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServiceResponse_Service); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_hosxp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hosxp_proto_goTypes,
		DependencyIndexes: file_proto_hosxp_proto_depIdxs,
		MessageInfos:      file_proto_hosxp_proto_msgTypes,
	}.Build()
	File_proto_hosxp_proto = out.File
	file_proto_hosxp_proto_rawDesc = nil
	file_proto_hosxp_proto_goTypes = nil
	file_proto_hosxp_proto_depIdxs = nil
}
